modules:
    star:
        type: 'shell'
        description: >
            Run single-pass STAR and generate coordinate-sorted BAM,
            with random multi-mapper selection and unmaped reads included
            in the output.
        command: >
            {exe} --runThreadN {threads} --genomeDir {index}
                --readFilesIn {fastq1} {fastq1}
                --outSAMtype BAM SortedByCoordinate
                --outStd BAM_SortedByCoordinate
                --outMultimapperOrder Random
                --outSAMunmapped Within KeepPairs
                {extra}
        param:
            exe:        'STAR executable, file:x, STAR'
            threads:    'Number of execution threads, int, 4'
            index:      'STAR index, str'
            fastq1:     'Read1 file, file:r:fastq'
            fastq2:     'Read2 file, file:r:fastq'
            extra:      'Extra parameters to pass to STAR, str'
pipelines:
    star-quad:
        description: >
            Run multiple instances of STAR in parallel (default=4) and merge
            the sorted BAMs.
        steps: ['input','split','star','merge']
        modules:
            split:  { instances: 4 }
    star-quad-sra:
        description: >
            Run multiple instances of STAR in parallel (default=4), each
            streaming independently from SRA, and merge the sorted BAMs.
        steps: ['split','input','star','merge']
        modules:
            split:  { instances: 4 }
            input:  { source: 'sra' }
